services:
  postgres:
    image: postgres
    restart: always
    container_name: docker-postgres
    volumes:
      - ./local_database/postgres-server:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
